services:
  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
  

  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "2000:2000"
    environment:
      MONGO_URL: mongodb://localhost:27017
    depends_on:
      - mongodb

  
volumes:
  mongo-data:
