# Use Node.js as base image
FROM node:23.1.0

# Set working directory
WORKDIR /Desktop/Documents/ImgDocker/BlogContainer

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install

# Copy the source code
COPY . .

# Expose backend port
EXPOSE 2000

# Start the backend server
CMD ["node", "main.js"]
